In [1]:
import tensorflow as tf

print("CuDNN version:", tf.sysconfig.get_build_info())

CuDNN version: OrderedDict([('is_cuda_build', False), ('is_rocm_build', False), ('is_tensorrt_build', False)])


In [2]:
import tensorflow as tf

print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  0


In [3]:
from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
len(test_labels)

10000

In [6]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
len(test_labels)

10000

In [9]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

In [11]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [12]:
train_images = train_images.reshape((60000, 28 * 28))  # Convert 2D (28 * 28) to 1D vector (28 * 28 = 764)
train_images = train_images.astype(
    "float32") / 255  # We’ll transform it into a float32 array of shape (60000, 28 * 28) with values between 0 and 1.

In [13]:
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float") / 255

In [14]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8710 - loss: 0.4356
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9660 - loss: 0.1179
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9789 - loss: 0.0719
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9850 - loss: 0.0503
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9890 - loss: 0.0379


In [15]:
test_digits = test_images[0:10]

In [16]:
predictions = model.predict(test_digits)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


In [17]:
predictions[0]

array([1.0733961e-07, 2.9962351e-08, 4.3116947e-06, 2.8915124e-04,
       9.5556452e-10, 7.0570749e-08, 6.5121362e-13, 9.9969661e-01,
       8.6406021e-07, 8.8864790e-06], dtype=float32)

In [18]:
predictions[0].argmax()

7

In [19]:
predictions[0][7]

0.9996966

In [20]:
test_labels[0]

7

In [21]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9761 - loss: 0.0746
test_acc: 0.9797000288963318
